config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }
  root to: 'dashboards#show'
  resource :users, only: %i[new create]
  post 'hooks/:integration_name' => 'webhooks#receive', as: :receive_webhooks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.create(params)
    super(params.to_hash)
  end

  def update(params)
    super(params.to_hash)
  end
end

app/models/card.rb
class Card < ApplicationRecord
  include GithubMethods

  belongs_to :column
  belongs_to :team_member
  belongs_to :issue, optional: true
  has_many :moves, class_name: 'CardMove', dependent: :destroy

  def move(to:, moved_by:, moved_at:)
    previos_move = moves.last
    moves.create(from: column, to: to, team_member: moved_by,
                 moved_at: moved_at, previos_move: previos_move)
    update(column: to, updated_on_github_at: moved_at)
  end

  def self.sync(json)
    struct = CardStruct.new(json)
    return if up_to_date?(struct)

    from_struct(struct)
  end

  def self.from_struct(struct)
    column = Column.find(struct.column_id)
    user = TeamMember.update_or_create(struct.creator)
    issue = Issue.from_struct(struct.issue) if struct.issue
    update_or_create(
      struct.with_params(column: column, team_member: user, issue: issue)
    )
  end
end

app/models/card_move.rb
class CardMove < ApplicationRecord
  include GithubMethods

  belongs_to :from, class_name: 'Column'
  belongs_to :to, class_name: 'Column'
  belongs_to :team_member
  belongs_to :card
  belongs_to :next_move, class_name: 'CardMove', optional: true

  has_one :previos_move, class_name: 'CardMove', inverse_of: 'next_move',
                         dependent: :nullify, foreign_key: 'next_move_id'
end

app/models/column.rb
class Column < ApplicationRecord
  include GithubMethods

  belongs_to :project
  has_many :cards, dependent: :destroy
  has_many :from_moves,
           class_name: 'CardMove', inverse_of: 'from',
           dependent: :destroy, foreign_key: 'from_id'
  has_many :to_moves,
           class_name: 'CardMove', inverse_of: 'to',
           dependent: :destroy, foreign_key: 'to_id'
end

app/models/concerns/github_methods.rb
module GithubMethods
  extend ActiveSupport::Concern

  class_methods do
    def up_to_date?(source)
      obj = find_by(id: source.id, updated_on_github_at: source.updated_on_github_at)
      obj.present?
    end

    def update_or_create(source)
      obj = find_by(id: source.id)
      if obj.nil?
        obj = create(source)
      elsif obj.updated_on_github_at != source.updated_on_github_at
        obj.update(source)
      end
      obj
    end
  end
end

app/models/issue.rb
class Issue < ApplicationRecord
  include GithubMethods
  scope :order_by_state, lambda {
                           order("CASE issues.state
                                    WHEN 'open'   THEN '1'
                                    WHEN 'closed' THEN '2'
                                  END")
                         }

  belongs_to :team_member
  has_one :card, dependent: :destroy
  belongs_to :assignee, class_name: 'TeamMember', optional: true

  def remove_assignee
    update(assignee: nil)
  end

  def self.sync(json)
    struct = IssueStruct.new(json)
    return if up_to_date?(struct)

    from_struct(struct)
  end

  def self.from_struct(struct)
    user = TeamMember.update_or_create(struct.user)

    assignee = TeamMember.update_or_create(struct.assignee) if struct.assignee
    update_or_create(
      struct.with_params(team_member: user, assignee: assignee)
    )
  end
end

app/models/project.rb
class Project < ApplicationRecord
  include GithubMethods

  belongs_to :team_member, optional: true
  has_many :columns, dependent: :destroy
end

app/models/team_member.rb
class TeamMember < ApplicationRecord
  include GithubMethods

  has_many :projects, dependent: :destroy
  has_many :cards, dependent: :destroy
  has_many :issues, dependent: :destroy
  has_many :card_moves, dependent: :destroy
  has_many :assignments, dependent: :nullify, inverse_of: 'assignee',
                         class_name: 'Issue', foreign_key: 'assignee_id'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :recoverable,
         :rememberable, :validatable, :omniauthable

  validates :first_name, presence: true
  validates :first_name, length: { in: 3..50 },
                         if: ->(c) { c.first_name.present? }
  validates :last_name, length: { in: 3..50 },
                        if: ->(c) { c.last_name.present? }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create(
      first_name: auth.info.name,
      provider: auth.provider,
      uid: auth.uid,
      email: auth.info.email,
      password: Devise.friendly_token[0, 20]
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def after_sign_out_path_for(_resource)
    new_user_session_path
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env['omniauth.auth'])
    sign_in(@user)
    redirect_to root_path
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  def show
    @team_members = UsersWithAssigniesQuery.call
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      flash[:success] = 'Signed in successfully.'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :verify_signature

  def receive
    HandleEventJob.perform_later event_type, payload
    render json: { received: true }, status: :ok
  end

  private

  def verify_signature
    return unless compare_signatures

    render 'Invalid signature', status: :unauthorized
  end

  def compare_signatures
    Rack::Utils
      .secure_compare(signature, request.headers['X-Hub-Signature'])
  end

  def signature
    'sha1=' + OpenSSL::HMAC.hexdigest(
      OpenSSL::Digest.new('sha1'),
      ENV['SECRET_TOKEN'],
      parse_data['payload']
    )
  end

  def payload
    Oj.load(parse_data['payload']).deep_symbolize_keys
  end

  def event_type
    request.headers['X-Github-Event']
  end

  def parse_data
    if request.headers['Content-Type'] == 'application/json'
      JSON.parse(request.body.read)
    else
      params.as_json
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
  def decorated_state(issue)
    state_style = case issue.state
                  when 'open' then 'text-success'
                  when 'closed' then 'text-danger'
                  else ''; end
    tag.p(issue.state, class: 'm-0 ' + state_style)
  end
end

app/views/card_moves/_card_move.html.slim
= card_move.timespan
br

app/views/dashboards/_no_projects.html.slim
.container.vh-100.d-flex.align-items-center
  h1.display-4 = "No projects found for \"#{@repo}\"" 

app/views/dashboards/show.html.slim
.users-container.d-flex.py-3.align-content-stretch
  = render @team_members

app/views/issues/_issue.html.slim
.container.border.mb-3.bg-white.rounded.p-2
  = link_to issue.html_url
    h4 = issue.title
  = decorated_state(issue)
  - unless issue.card.nil? || issue.card.moves.empty?
    hr
    = render CardMoveDecorator.decorate_collection(issue.card.moves)

app/views/layouts/_flash.html.slim
.container
  - flash.each do |message_type, message|
    = content_tag(:div, message, class: "alert alert-#{message_type} mt-2")

app/views/layouts/_menu.html.slim
nav.navbar.navbar-expand-lg
  .container
    ul.navbar-nav.ml-auto
      - if current_user
        li.sign-btn
          = link_to destroy_user_session_path, method: :delete, class: 'btn btn-dark'
            | Sign out
      - else
        li.nav_item.sign-in-btn
          = link_to new_user_session_path, class: 'btn btn-dark nav-sign-in-btn'
            | Sign in
        li.nav_item.sign-up-btn
          = link_to new_users_path, class: 'btn btn-dark nav-sign-in-btn'
            | Sign up

app/views/layouts/application.html.slim
doctype html
html
  head
    title PawStatistics
    = csrf_meta_tags
    = csp_meta_tag

    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'layouts/menu'
    = render 'layouts/flash'
    = yield

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation class='alert alert-danger'
    div
      | The form contains #{pluralize(object.errors.count, "error")}:
    ul
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/team_members/_team_member.html.slim
.h-100.bg-light.border.mx-2.rounded.user-column.py-2.px-3.overflow-hidden
  h2= team_member.login
  .cards-columns
    = render team_member.assignments

app/views/users/_user.html.slim
.h-100.bg-light.border.mx-2.rounded.user-column.py-2.px-3.overflow-hidden
  h2= user.login
  .cards-columns
    = render user.assignments

app/views/users/new.html.slim
.container
  .row.justify-content-center  
    .col-6
      h2.title Sign up
      = simple_form_for @user do |f|
        = render 'shared/error_messages', object: f.object
        .form-group
          = f.input :first_name, label: 'First name', placeholder: 'Your first name', input_html: { class: 'form-control' }, error: false
        .form-group
          = f.input :last_name, label: 'Last name', placeholder: 'Your last name', input_html: { class: 'form-control' }, error: false
        .form-group
          = f.input :email, placeholder: 'user@domain.com', input_html: { class: 'form-control' }, error: false
        .form-group
          = f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                      input_html: {autocomplete: "new-password", class: 'form-control'}, error: false
        .form-group
          = f.input :password_confirmation, required: true, input_html: {autocomplete: "new-password", class: 'form-control'}, error: false
        .form-group
          = f.submit 'Submit', class: 'btn btn-primary'